fix(avo-2961): fix jenkins parallel statement

diff --git a/openshift/Jenkinsfile b/openshift/Jenkinsfile
--- a/openshift/Jenkinsfile
+++ b/openshift/Jenkinsfile
@@ -58,100 +58,96 @@ pipeline {
 			}
 		}
 
-		stage('Build ui and api in parallel') {
-			steps {
-				parallel(
-					stage('ui') {
-						steps {
-							container('npm') {
-								// Build ui
-								script {
-									sh '''
-										#!/bin/bash
-										node -v
-										npm -v
-										npm --registry=https://registry.npmjs.org install
-										cd ui
-										npm --registry=https://registry.npmjs.org install
-										npm run build || exit 1
-										cd ..
-									'''
-								} // end script Build ui
+		parallel(
+			stage('ui') {
+				steps {
+					container('npm') {
+						// Build ui
+						script {
+							sh '''
+								#!/bin/bash
+								node -v
+								npm -v
+								npm --registry=https://registry.npmjs.org install
+								cd ui
+								npm --registry=https://registry.npmjs.org install
+								npm run build || exit 1
+								cd ..
+							'''
+						} // end script Build ui
 
-								// Publish ui
-								script {
-									try {
-										echo "Publishing admin-core-ui package to registry"
-										configFileProvider([configFile(fileId: "npmrc", variable: 'configFile')]) {
-											sh "cat $configFile > .npmrc"
-										}
-										sh '''
-													#/bin/bash
-													cp .npmrc ./ui
-													cd ui
-													npm config fix
-													npm publish
-													rm -f .npmrc
-													cd ..
-												'''
-									} catch (err) {
-										echo "Error message: ${err.getMessage()}"
-										if (err.getMessage().contains("Repository does not allow updating assets")) {
-											echo "admin-core-ui package version number was not updated, continuing with api build"
-										} else {
-											echo "admin-core-ui package failed to publish"
-											currentBuild.result = 'FAILURE'
-										}
-									}
-								} // end script Publish ui
-							}
-						}
-					},
-					stage('api') {
-						steps {
-							container('npm') {
-								// Build api
-								script {
-									sh '''
-										#!/bin/bash
-										cd api && npm --registry=https://registry.npmjs.org install && npm run build && cd .. || exit 1
-									'''
-								} // end script Build api
-
-								// Publish api
-								script {
-									try {
-										echo "Publishing admin-core-api package to registry"
-										configFileProvider([configFile(fileId: "npmrc", variable: 'configFile')]) {
-											sh "cat $configFile > .npmrc"
-										}
-										sh '''
+						// Publish ui
+						script {
+							try {
+								echo "Publishing admin-core-ui package to registry"
+								configFileProvider([configFile(fileId: "npmrc", variable: 'configFile')]) {
+									sh "cat $configFile > .npmrc"
+								}
+								sh '''
 											#/bin/bash
-											cp .npmrc ./api
-											cd api
+											cp .npmrc ./ui
+											cd ui
 											npm config fix
 											npm publish
 											rm -f .npmrc
 											cd ..
-											echo "removing .npmrc for installto nexus not seems @viaa:registry=.."
-											rm -f .npmrc
 										'''
-									} catch (err) {
-										echo "Error message: ${err.getMessage()}"
-										if (err.getMessage().contains("Repository does not allow updating assets")) {
-											echo "admin-core-api package version number was not updated, continuing with pipeline"
-										} else {
-											echo "admin-core-api package failed to publish"
-											currentBuild.result = 'FAILURE'
-										}
-									}
-								} // end script Publish api
+							} catch (err) {
+								echo "Error message: ${err.getMessage()}"
+								if (err.getMessage().contains("Repository does not allow updating assets")) {
+									echo "admin-core-ui package version number was not updated, continuing with api build"
+								} else {
+									echo "admin-core-ui package failed to publish"
+									currentBuild.result = 'FAILURE'
+								}
 							}
-						}
-					},
-				)
-			}
-		}
+						} // end script Publish ui
+					}
+				}
+			},
+			stage('api') {
+				steps {
+					container('npm') {
+						// Build api
+						script {
+							sh '''
+								#!/bin/bash
+								cd api && npm --registry=https://registry.npmjs.org install && npm run build && cd .. || exit 1
+							'''
+						} // end script Build api
+
+						// Publish api
+						script {
+							try {
+								echo "Publishing admin-core-api package to registry"
+								configFileProvider([configFile(fileId: "npmrc", variable: 'configFile')]) {
+									sh "cat $configFile > .npmrc"
+								}
+								sh '''
+									#/bin/bash
+									cp .npmrc ./api
+									cd api
+									npm config fix
+									npm publish
+									rm -f .npmrc
+									cd ..
+									echo "removing .npmrc for installto nexus not seems @viaa:registry=.."
+									rm -f .npmrc
+								'''
+							} catch (err) {
+								echo "Error message: ${err.getMessage()}"
+								if (err.getMessage().contains("Repository does not allow updating assets")) {
+									echo "admin-core-api package version number was not updated, continuing with pipeline"
+								} else {
+									echo "admin-core-api package failed to publish"
+									currentBuild.result = 'FAILURE'
+								}
+							}
+						} // end script Publish api
+					}
+				}
+			},
+		)
 
 
 //		stage('Build ui code') {
